# Used for Developing under VSCode
services:
    elixir_pinger:
        image: ping-minion-dev:latest
        build:
            context: .        
            dockerfile: dev/Dockerfile    
        